[tool.poetry]
name = "movie-recsys-pro"
version = "0.1.0"
description = "Buscador Semántico Multimodal"
authors = ["Felix Lezama"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "1.31.0"
qdrant-client = "1.7.0"
google-genai = "0.3.0"
pydantic = "2.6.1"
pydantic-settings = "2.1.0"
loguru = "0.7.2"
tqdm = "4.66.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"