[tool.poetry]
name = "movie-recsys-pro"
version = "0.1.0"
description = "Buscador Semántico Multimodal"
authors = ["Felix Lezama"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "*"
qdrant-client = "*"
google-genai = "*"
pydantic = "^2.0"
pydantic-settings = "*"
loguru = "*"
tqdm = "*"
altair = "*"
pandas = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"